reduce data 30%
odroidodroid/bevfusion_cap pull request #1
Opened 2024-10-10 07:19 UTC by odroidodroid

@leejisup @JWHer 

reducing dataset

2024-10-10 09:00 UTC, JWHer requested changes
몇가지 좀 자잘한 타이핑이나 지울것들이 있어서 봐줘. 머지 컨플릭도 있는데 이거 한번 같이 보자.

`for sample in mmcv.track_iter_progress(nusc.sample):` 여기에서 scene_token별로 이터레이션 도는게 아니여서 이렇게 코드가 나오는구나. 이제 이해했음

2024-10-10 09:00 UTC, JWHer commented on tools/create_data.py
여기 지워도 될꺼같아.

로컬에서 yjkim 브랜치로 checkout하고,
이 파일(tools/create_data.py)에서 아래 수정사항 다 확인해서 반영하고,
커밋하고,
git push caplab해줘.

이제 force push 안해도 잘 올라갈듯

2024-10-10 09:00 UTC, JWHer commented on tools/create_data.py
> +        f"{out_dir}/{info_prefix}_reduced{reduce_ratio}_infos_train_v1.pkl",
이름 잘 지은거같다. 근데 뒤에 v1은 우리가 결정적(deterministic)하게 샘플해서 없어도 될거같아. `{out_dir}/{info_prefix}_reduced{reduce_ratio}_infos_train.pkl` 까지가 어떨까?

2024-10-10 09:00 UTC, JWHer commented on tools/create_data.py
> +parser.add_argument("--reduce-ratio", type=int, default=30)
이건 float 입력을 받기 힘들어서 30 integer로 한건가? 우리는 100 기준을 알아서 상관없긴 한데.

2024-10-10 09:00 UTC, JWHer commented on tools/data_converter/nuscenes_converter.py
> +                          max_radar_sweeps=10,
rader가 있는데 지워도 될거같아.

2024-10-10 09:00 UTC, JWHer commented on tools/data_converter/nuscenes_converter.py
> +        nusc, train_scenes, val_scenes, test, max_sweeps=max_sweeps, max_radar_sweeps=max_radar_sweeps, reduce_ratio=reduce_ratio)
마찬가지로 rader 지워줘

2024-10-10 09:00 UTC, JWHer commented on tools/data_converter/nuscenes_converter.py
> +                             '{}_reduced{}_infos_train_v1.pkl'.format(info_prefix, reduce_ratio))
위에 커멘트했는데. v1을 붙어야 할까? 지금 보니까 수정사항이 많아보여서 그냥 두는것도 나을듯.

2024-10-10 09:00 UTC, JWHer commented on tools/data_converter/nuscenes_converter.py
> +                                 '{}_infos_val_v1.pkl'.format(info_prefix))
여기도 v1문제.

2024-10-10 09:00 UTC, JWHer commented on tools/data_converter/nuscenes_converter.py
> +                         max_radar_sweeps=10,
레이더 빼줘.

2024-10-10 09:00 UTC, JWHer commented on tools/data_converter/nuscenes_converter.py
> -        )["location"]
이게 빠진거같아. location이 있어야 할거같은데. 이 세라인 복원해줄래?

2024-10-10 09:00 UTC, JWHer commented on tools/data_converter/nuscenes_converter.py
> -            "location": location,
이것도 마찬가지로 복원해줘

2024-10-10 09:00 UTC, JWHer commented on tools/data_converter/nuscenes_converter.py
> +        if sample['scene_token'] in train_scenes:
여긴 내용이 바뀐게 아니라 코드 포맷팅이 된거같은데. 다시 돌려줄 수 있을까?
포맷팅 변경이 포함되면 리뷰하기 힘들어서.

2024-10-10 12:27 UTC, odroidodroid commented on tools/data_converter/nuscenes_converter.py
> +                          max_radar_sweeps=10,
수정 완료!

2024-10-10 12:27 UTC, odroidodroid commented on tools/data_converter/nuscenes_converter.py
> +        nusc, train_scenes, val_scenes, test, max_sweeps=max_sweeps, max_radar_sweeps=max_radar_sweeps, reduce_ratio=reduce_ratio)
수정 완료!

2024-10-10 12:28 UTC, odroidodroid commented on tools/data_converter/nuscenes_converter.py
> +                             '{}_reduced{}_infos_train_v1.pkl'.format(info_prefix, reduce_ratio))
어차피 마지막꺼만 계속 쓸 것 같아서 _v1은 지웠어

2024-10-10 12:28 UTC, odroidodroid commented on tools/data_converter/nuscenes_converter.py
> -            "location": location,
수정완료

2024-10-10 12:29 UTC, odroidodroid commented on tools/data_converter/nuscenes_converter.py
> +                         max_radar_sweeps=10,
수정완료

2024-10-10 12:29 UTC, odroidodroid commented on tools/data_converter/nuscenes_converter.py
> +                                 '{}_infos_val_v1.pkl'.format(info_prefix))
수정 완료

2024-10-10 12:29 UTC, odroidodroid commented on tools/create_data.py
> +parser.add_argument("--reduce-ratio", type=int, default=30)
float이 더 직관적이어서 float으로 바꿨어

2024-10-10 12:29 UTC, odroidodroid commented on tools/create_data.py
> +        f"{out_dir}/{info_prefix}_reduced{reduce_ratio}_infos_train_v1.pkl",
수정완료

2024-10-10 12:30 UTC, odroidodroid commented on tools/data_converter/nuscenes_converter.py
> -        )["location"]
수정 완료

2024-10-10 12:41 UTC, odroidodroid commented on tools/data_converter/nuscenes_converter.py
> +        if sample['scene_token'] in train_scenes:
수정 완료

2024-10-10 13:12 UTC, JWHer approved these changes
자잘한 오류가 있는데, 좀만 더 고치면 좋을거같아. 수고했어~

2024-10-10 13:12 UTC, JWHer commented on tools/data_converter/nuscenes_converter.py
> +    selected_frame_range = [np.linspace(0, scene_frame_num[i]-1, reduced_frame_num[i], dtype=int) for i in range(len(scene_frame_num))]
좋은 함수네, ratio가 1 이상이 안되게 체크할 필요는 없겠지? 👍

2024-10-10 13:12 UTC, JWHer commented on tools/data_converter/nuscenes_converter.py
> +        if cnt not in selected_frame_range[scene].tolist() :
중요한건 아닌데, 여기서 tolist()하는것보다 selected_frame_range 이거 만들때 tolist() 붙이는게 나을듯

2024-10-10 13:12 UTC, JWHer commented on tools/data_converter/nuscenes_converter.py
> +            cnt += 1
cnt+=1도 202번 if문 위에 두면 하나만 써도 될듯.

        cnt += 1
        if cnt not in selected_frame_range[scene].tolist() :
            continue
            
이렇게 세줄로

2024-10-10 13:12 UTC, JWHer commented on tools/data_converter/nuscenes_converter.py
> -                    (anno["num_lidar_pts"] + anno["num_radar_pts"]) > 0
이건 잘못바뀐거같은데. 한번 확인해줄래?

2024-10-10 13:21 UTC, odroidodroid commented on tools/data_converter/nuscenes_converter.py
> +            cnt += 1
cnt를 if문 위에 두면 cnt 값이 바뀌어서 그렇게 한건데 initial cnt를 -1로 만들면 되려나

2024-10-10 13:31 UTC, odroidodroid commented on tools/data_converter/nuscenes_converter.py
> -                    (anno["num_lidar_pts"] + anno["num_radar_pts"]) > 0
아 실수했다!! radar라서 그냥 지워버렸네. 안바꾸는게 맞아!

2024-10-10 13:31 UTC, odroidodroid commented on tools/data_converter/nuscenes_converter.py
> +        if cnt not in selected_frame_range[scene].tolist() :
수정 완료

2024-10-10 13:31 UTC, odroidodroid commented on tools/data_converter/nuscenes_converter.py
> +    selected_frame_range = [np.linspace(0, scene_frame_num[i]-1, reduced_frame_num[i], dtype=int) for i in range(len(scene_frame_num))]
음 아무래도 그럴 것 같아

2024-10-10 17:09 UTC, odroidodroid commented
@JWHer @leejisup 
reduced0.3 pkl 파일로 train은 잘 되는데 validation 후에 evaluation하면 에러가 나서 수정했어. 
evaluation에서는 data info가 아니라 nusc 라이브러리에서 모든 샘플을 가져오기 때문에 줄어든 데이터셋이 반영되지 않아가지고..
그래서 바꾼 부분은
(1) config에 reduce_ratio 추가
(2) mmdet3d/datasets/nuscenes_dataset.py 에서 GT 가져올때 모든 데이터샘플을 안가지고 오도록 수정
- 이때 라이브러리를 타고 들어가야 해서 DetectEval은 상속받고 load_gt를 수정해서 data info를 가져왔어
- data info를 처음에 build_dataset할때 가져오지만 그때 data info는 class 변수로 안들어가길래 그렇게 한 이유가 있을 것 같아서 한번 더 가져오기로 함

2024-10-11 02:03 UTC, leejisup approved these changes
수정한 부분 확인했음!

2024-10-11 07:19 UTC, merged