Leejs
odroidodroid/bevfusion_cap pull request #4
Opened 2024-10-15 05:22 UTC by leejisup

Crossover, mutation 추가
evalKnapsack 부분은 train.py 파일에서 학습하는 코드를 가져옴

[To Do]
mmdet3d/apis/train.py 의 train_model 함수가 mAP, latency를 리턴하도록 변경
config 파일 입력, 학습 후 변경 하도록 작성

2024-10-28 08:32 UTC, leejisup commented
chromosome.py 파일에 crossover, mutation 추가
main.py 에서 import 하여 사용

2024-10-28 11:35 UTC, JWHer approved these changes
수고했어. 커맨트 확인해봐.

2024-10-28 11:35 UTC, JWHer commented on ga/genes/chromosome.py
> +    "model.encoders.lidar.backbone.output_channels": encoder_lidar_backbone_output_channels,
오타인거같은데

2024-10-28 11:35 UTC, JWHer commented on ga/genes/chromosome.py
> +    for i in range(len(points)-1):
points가 indice를 의미하지 않나? 굳이 range를 안쓰고 for i in points하면 될거같은데.

2024-10-28 11:35 UTC, JWHer commented on ga/genes/chromosome.py
> +        if i % 2 == 0:
이거의 의미는 뭐지..? child1과 child2를 나누어서 ind1, ind2를 할당하는 의미가 있나? child 순서는 아무 의미가 없어보이는데.

2024-10-28 11:35 UTC, JWHer commented on ga/genes/chromosome.py
> +            for j in range(points[i], points[i+1]):
마찬가지로 points 값이 indice인데 굳이 range를 사용하지 않아도 될거같아.

2024-10-28 11:35 UTC, JWHer commented on ga/genes/chromosome.py
> +    child2.update(parameters)
업데이트 함수의 정확한 작동을 알고 제대로 고쳐줘. 이렇게 사용하면 안될거같아.

2024-10-28 11:35 UTC, JWHer commented on ga/genes/chromosome.py
> +    point = random.randint(0, len(keys)-1)
이 구문은 key = random.choice(search_space.keys()) 한 문장으로 교체 가능할거 같아.

2024-10-28 11:35 UTC, JWHer commented on ga/genes/chromosome.py
> +    chromosome[keys[point]] = generate_chromosome()[keys[point]]
이 구문은 chromosome[key] = search_space[key]()로 고쳐야 할 것 같아. 또 이렇게 작성하면 deps가 제대로 해결이 안될거같은데?

chromosome.update(dependent_keys) 하고 for문을 돌면서 deps 해결하는 구문이 추가되어야 해.

2024-10-28 11:35 UTC, JWHer commented on ga/main.py
> +    #    return individual,
안쓰는 코드는 지워도 될거같아.

2024-10-28 11:37 UTC, JWHer requested changes
수정을 해야할거같아. 검증을 하고 리뷰를 하는게 맞는거같다.

2024-10-28 23:43 UTC, leejisup commented on ga/genes/chromosome.py
> +    for i in range(len(points)-1):
82line의 points는 crossover가 일어날 포인트 2개를 리스트로 저장한거고 그 포인트를 편의 상 point1, point2라 하면 for 문에서 하는 일은 0~point1, point1~point2, point2~마지막 이렇게 구간을 분리하고, point1~point2 구간에만  ind2 -> child1, ind1 -> child2로 crossover, 나머지는 ind1 -> child1, ind2 -> child2로 그대로 복사하는 방식으로 구현했어.

2024-10-28 23:45 UTC, leejisup commented on ga/genes/chromosome.py
> +    child2.update(parameters)
dependent한 key만 업데이트 하도록 수정할게

2024-10-28 23:57 UTC, leejisup commented on ga/genes/chromosome.py
> +    chromosome[keys[point]] = generate_chromosome()[keys[point]]
이 부분은 crossover에만 구현하고 여길 안했네.. 추가함

2024-10-29 00:03 UTC, leejisup commented
한번 학습 돌려보고 올리도록 할게.

2024-10-30 05:13 UTC, leejisup commented
로그 읽어서 crossover, mutation 작동 확인하고 올렸음.

2024-10-30 06:58 UTC, JWHer approved these changes
수고했어~

2024-10-31 03:49 UTC, merged