ga individual train result 저장
odroidodroid/bevfusion_cap pull request #9
Opened 2024-10-28 08:54 UTC by odroidodroid

@JWHer @leejisup 
1. main.py의 evalknapsack에서 individual의 result(latency랑 accracy) 저장은 일단 기존 config파일에 하도록 했는데 따로 yaml 파일을 만들어서 result만 listing하는게 나을까? 의견 부탁해. 
2. evalknapsack에 subprocess 부분은 따로 함수로 만드는게 나을 것 같아서 algo.py의 run_model로 만들었어.
3. custom_easimple을 주간보고에 따라 수정하긴 했는데 보완이 필요.
4. 다음 generation에서 같은 individual이 등장했을 때 pass하는 부분은 곧 commit할게.

2024-10-28 11:20 UTC, JWHer requested changes
main.py의 evalknapsack에서 individual의 result(latency랑 accracy) 저장은 일단 기존 config파일에 하도록 했는데 따로 yaml 파일을 만들어서 result만 listing하는게 나을까?
=> config 파일 의미는 학습 실행을 위한 설정이여서, 결과를 저장하려면 따로 파일을 만들어 저장하는게 좋을 거 같아.

evalknapsack에 subprocess 부분은 따로 함수로 만드는게 나을 것 같아서 algo.py의 run_model로 만들었어.
=> lgtm

custom_easimple을 주간보고에 따라 수정하긴 했는데 보완이 필요.
=> 이거 이름하고 작동이 아직 이상한거같은데. 아직 완성이 안된건가? 커멘트 확인해줘.

2024-10-28 11:20 UTC, JWHer commented on ga/algo.py
> +    return get_map(run_dir), latency
순서가 반대로됬어. `creator.create("Fitness", base.Fitness, weights=(-1.0, 1.0))` fitness weight 보면 부정적인 요소가 앞에 있어야해.

2024-10-28 11:20 UTC, JWHer commented on ga/main.py
> -            save_checkpoint(pop, hof, logbook, gen)
save_checkpoint가 custom easimple에서 누락되어있는데.

2024-10-28 11:20 UTC, JWHer commented on ga/algo.py
> +from ga.utils import write_stds, logger, get_map
isort(import sort) 해서 올려줘. vscode에 isort extention 있어.

2024-10-28 11:20 UTC, JWHer commented on ga/main.py
>              )
ngen을 1로 주고 for loop를 도는건 save_checkpoint하려고 한 세대씩 돌린건데, custom 함수를 사용하면 굳이 for loop를 유지할 필요가 없을거같아.

2024-10-28 11:20 UTC, JWHer commented on ga/algo.py
> +                   halloffame=None, verbose=__debug__) :
이거 eaMuPlusLambda를 수정한거면 이름이 custom_eaSimple이 아니고 custom_eaMuPlusLambda가 되야하지 않을까?

2024-10-28 11:20 UTC, JWHer commented on ga/algo.py
> +            print(logbook.stream)
여기서 iteration 돌때마다 save_checkpoint 해야할거같은데.

2024-10-28 11:20 UTC, JWHer commented on ga/main.py
> +            yaml.dump(config_dict, f)
결과를 따로 저장하는건 좋은데, 왜 설정파일에 결과를 합쳐? 따로 저장하도록 수정하는게 좋을거같아. 저장 경로도 바꿔줘.

2024-10-28 17:18 UTC, odroidodroid commented on ga/algo.py
> +    return get_map(run_dir), latency
수정 완료!

2024-10-28 17:20 UTC, odroidodroid commented on ga/main.py
> -            save_checkpoint(pop, hof, logbook, gen)
실수로 지운듯! 수정함!

2024-10-28 17:20 UTC, odroidodroid commented on ga/main.py
>              )
처음에 수정했었는데 코드 다시 pull해서 합치다가 까먹었네.. 수정함!

2024-10-28 17:21 UTC, odroidodroid commented on ga/algo.py
> +                   halloffame=None, verbose=__debug__) :
오키!!

2024-10-28 17:21 UTC, odroidodroid commented on ga/algo.py
> +            print(logbook.stream)
수정함!

2024-10-28 17:22 UTC, odroidodroid commented on ga/main.py
> +            yaml.dump(config_dict, f)
오키! 수정함!

2024-10-28 17:22 UTC, odroidodroid commented on ga/algo.py
> +from ga.utils import write_stds, logger, get_map
수정함!!

2024-10-28 19:03 UTC, odroidodroid commented
- GA 클래스의 crossover, mutation, evalknapsack 함수들이 클래스에서 공유하는 변수가 없는 것 같아서 빼도 되지 않을까? 
- evalKnapsack에서 current_generation, current_individual 받아올 때만 클래스 변수를 쓸 것 같은데, 클래스 변수로 두지 않아도 받을 수 있긴 해서, custom_eaMuPlusLambda를 수정해놨어. 
- 만약 evalKnapsack의 current_generation과 current_individual을 클래스 변수로 받아오려면 custom_eaMuPlusLambda도 클래스 함수로 넣어줘야 받을 수 있어.

2024-10-31 14:33 UTC, odroidodroid reviewed
@JWHer @leejisup 
train dataloader를 test하면서 loss를 받아서 loss가 큰 것들을 train 하도록 dataset을 줄이는 코드

2024-10-31 14:35 UTC, odroidodroid commented on mmdet3d/models/fusion_models/bevfusion.py
bevfusion.py에서 return loss 인자가 이미 있는데 안쓰이길래 추가해서 test일때도 return_loss가 True이면 loss 반환하게 함

2024-10-31 14:37 UTC, odroidodroid commented on prune_dataset_loss/prune.py
single_gpu_test 수정해서 loss 받아오도록 함.
cnt는 실험할 때 쓴건데 뒤에서 지웠어.
ascending으로 하면 loss가 작은 것들로 저장되고, descending으로 하면 loss가 큰 것들이 저장돼.
ascending=False를 default로 수정할게.

2024-10-31 14:42 UTC, odroidodroid commented on tools/create_data.py
정원이가 수정하기 전에 고쳤던 코드인데, 뒤에 커밋에서 merge되도록 수정해놨어. 
pruning 방법이 두가지라서 prune_cfg로 따로 저장하고, prune method는 loss 또는 ratio야.
loss로 자르게 되면 tools/prune_dataset.py를 먼저 실행시켜서 loss/prune0.x.json 파일을 얻고, 그 파일 path를 여기에 token-list의 인자로  넣어줘. 자세히는 README에 적어둘게.

2024-10-31 14:44 UTC, odroidodroid commented on tools/data_converter/nuscenes_converter.py
json 파일에 token이 sample token과 일치하면 info를 만들어.

2024-10-31 14:46 UTC, odroidodroid commented on tools/prune_dataset.py
debug 코드는 뒤에 커밋에서 제거했어.
loss-dir는 nuscenens_converter.py에서 token-list를 저장하는 디렉토리야. 헷갈릴 수 있으니 ㅔ-pruned-token-dir로 수정할까 싶어.

2024-10-31 14:49 UTC, odroidodroid commented on ga/algo.py
디버깅 해봤는데 custom_eaMuPlusLambda를 class로 넣지 않는 이상은 current generation을 evalKnapsack에서 얻을 수 없어서 다시 아래처럼 수정했어.

2024-10-31 14:50 UTC, odroidodroid commented on ga/main.py
result 저장 코드는 save_results로 ga/utils/resume.py에 넣어놨어

2024-10-31 14:50 UTC, odroidodroid commented on ga/utils/resume.py
result 저장 코드야.

2024-10-31 15:10 UTC, odroidodroid commented on tools/prune_dataset.py
loss는 한번만 계산하면 되는거라 prune_ratio를 리스트로 만들어서 loss가 큰 토큰 저장하게 했어.

2024-10-31 15:11 UTC, odroidodroid commented on prune_dataset_loss/prune.py
loss는 한번만 계산하면 되는거라 prune_ratio를 리스트로 만들어서 loss가 큰 토큰 저장하게 했어.

2024-11-01 03:25 UTC, JWHer reviewed
잘 짰는데, 코드 버전 관리 측면으로 좀 이상하네. 같이 확인해보자.

2024-11-01 03:25 UTC, JWHer commented on configs/nuscenes/det/centerhead/lssfpn/camera/256x704/resnet/default.yaml
이 파일은 빼줄 수 있어? 중복되는것 같아서.

2024-11-01 03:25 UTC, JWHer commented on ga/algo.py
> +    # conda_activate = f"conda activate {conda_env}"
이거는 주석처리 하기보다, config에 옵션을 하나 만들어 줄 수 있어? CONDA_ENV 설정이 있어서, None이면 안하고 str이 있으면 실행하고.

2024-11-01 03:25 UTC, JWHer commented on ga/algo.py
> +    fitnesses = toolbox.map(toolbox.evaluate, invalid_ind, range(0, len(invalid_ind)), [0]*len(invalid_ind))
질문: range(0, len(invalid_ind)), [0]*len(invalid_ind) 이건 각각 뭘 의미하는거야? ind_idx, gen?/fitness?인가?

아래는 코드가 좀 예뻤으면 해서 첨언
```
invalid_ind_len = len(invalid_ind)
fitnesses = toolbox.map(toolbox.evaluate, invalid_ind, range(invalid_ind_len), [0]*invalid_ind_len
```

2024-11-01 03:25 UTC, JWHer commented on ga/algo.py
> +        fitnesses = toolbox.map(toolbox.evaluate, invalid_ind, range(0, len(invalid_ind)), [gen]*len(invalid_ind))
이것도 ind_idx, gen 표시용이지?

2024-11-01 03:25 UTC, JWHer commented on ga/algo.py
> +        population[:] = toolbox.select(population + offspring, mu)
이거 알고리즘을 설명해 줄 수 있어?

2024-11-01 03:25 UTC, JWHer commented on ga/algo.py
> +    return latency, mAP
여기는 주의해서 머지해야겠다.

2024-11-01 03:25 UTC, JWHer commented on ga/genes/chromosome.py
이 파일도 주의해서 머지해야겠다.

2024-11-01 03:25 UTC, JWHer commented on mmdet3d/datasets/nuscenes_dataset.py
> +        if self.reduce_ratio != 0 or self.reduce_ratio != 1:
여기도 이게 최신 코드가 아닌거같은데 이상하네.

2024-11-01 03:25 UTC, JWHer commented on mmdet3d/models/fusion_models/bevfusion.py
> +        return_loss=False,
이렇게 하면 기존 코드와 호환성 있고 잘 한거같다!

2024-11-01 03:25 UTC, JWHer commented on mmdet3d/ops/spconv/structure.py
이 코드의 목적을 한번 설명해 줄 수 있어? 프루닝할때 썼던건가? 이 파일이 문제를 일으키는것 같아.

2024-11-01 03:25 UTC, JWHer commented on tools/prune_camera.py
> +wandb.init(project='bevfusion_cap')
이 코드는 지워줘.

2024-11-01 03:25 UTC, JWHer commented on tools/prune_camera_spartan.py
> +wandb.init(project='bevfusion_cap')
이 코드도 지워줘

2024-11-01 03:25 UTC, JWHer commented on ga/main.py
>          logger.info(f"{individual=}")
이 코드가 왜 남아있지.. 좀 이상한거같아.

2024-11-01 03:25 UTC, JWHer commented on tools/prune_lidar.py
> +wandb.init(project='bevfusion_cap')
이것도 지워줘

2024-11-01 03:25 UTC, JWHer commented on tools/train.py
> +wandb.init(project='bevfusion_cap')
이것도 지워줘.

2024-11-01 04:00 UTC, odroidodroid commented on tools/train.py
> +wandb.init(project='bevfusion_cap')
확인!

2024-11-01 04:00 UTC, odroidodroid commented on tools/prune_lidar.py
> +wandb.init(project='bevfusion_cap')
확인!

2024-11-01 04:01 UTC, odroidodroid commented on tools/prune_camera_spartan.py
> +wandb.init(project='bevfusion_cap')
확인!

2024-11-01 04:01 UTC, odroidodroid commented on tools/prune_camera.py
> +wandb.init(project='bevfusion_cap')
확인!

2024-11-01 04:01 UTC, odroidodroid commented on ga/algo.py
> +    # conda_activate = f"conda activate {conda_env}"
확인!

2024-11-01 04:01 UTC, odroidodroid commented on ga/algo.py
> +    fitnesses = toolbox.map(toolbox.evaluate, invalid_ind, range(0, len(invalid_ind)), [0]*len(invalid_ind))
확인!

2024-11-01 04:02 UTC, odroidodroid commented on ga/algo.py
> +        fitnesses = toolbox.map(toolbox.evaluate, invalid_ind, range(0, len(invalid_ind)), [gen]*len(invalid_ind))
맞아

2024-11-01 04:02 UTC, odroidodroid commented on mmdet3d/datasets/nuscenes_dataset.py
> +        if self.reduce_ratio != 0 or self.reduce_ratio != 1:
머지 할때 잘못 된 것 같아. 최신 코드로 수정할게.

2024-11-01 04:03 UTC, odroidodroid commented on mmdet3d/models/fusion_models/bevfusion.py
> +        return_loss=False,
확인

2024-11-01 04:06 UTC, odroidodroid commented on configs/nuscenes/det/centerhead/lssfpn/camera/256x704/resnet/default.yaml
확인

2024-11-01 04:29 UTC, odroidodroid commented on mmdet3d/ops/spconv/structure.py
lidar pruning 할때 고친 코드야. 문제 있으면 원래대로 되돌릴게.

2024-11-01 04:29 UTC, JWHer approved these changes

2024-11-01 04:32 UTC, JWHer approved these changes
고치느라 수고했어~!

2024-11-01 04:32 UTC, odroidodroid commented on ga/algo.py
> +        population[:] = toolbox.select(population + offspring, mu)
eaMuPlusLambda를 가져온건데 eaSimple과 달리 다음 generation에서 기존 population + offspring을 더한 것에서 mu만큼 뽑는것 말고는 나도 잘 모르겠어. varAnd가 아니라 varOr인 것도 차이점이야.

2024-11-01 04:33 UTC, merged